FROM node:24-alpine

# set current directory
WORKDIR /app

# install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# don't copy source code here since it's mounted as volume

# run development server
CMD ["npm", "run", "dev"]
