FROM node:20-alpine

# set current directory
WORKDIR /app

# install dependencies
COPY package.json yarn.lock ./
RUN yarn

# don't copy source code here since it's mounted as volume

# run development server
CMD ["yarn", "dev"]