apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvizle-dz-2026
  labels:
    app: kvizle-dz-2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvizle-dz-2026
  template:
    metadata:
      labels:
        app: kvizle-dz-2026
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: kvizle-dz-2026-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: kvizle-dz-2026-backend
          volumeMounts:
            - name: kvizle-dz-2026-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvizle.settings.k8s
          envFrom:
            - secretRef:
                name: kvizle-dz-2026-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
        - name: migrate
          image: kvizle-dz-2026-backend
          volumeMounts:
            - name: kvizle-dz-2026-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - migrate
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvizle.settings.k8s
          envFrom:
            - secretRef:
                name: kvizle-dz-2026-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
      containers:
        - name: kvizle-dz-2026-backend
          image: kvizle-dz-2026-backend
          volumeMounts:
            - name: kvizle-dz-2026-storage
              mountPath: /storage
          command:
            - gunicorn
            - kvizle.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "90"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kvizle.settings.k8s
          envFrom:
            - secretRef:
                name: kvizle-dz-2026-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 800Mi
              cpu: 400m
        - name: kvizle-dz-2026-frontend
          image: kvizle-dz-2026-frontend
          volumeMounts:
            - name: kvizle-dz-2026-storage
              mountPath: /usr/share/nginx/html/backend-storage
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
