apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manipulacija
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.manipulacija.lb.djnd.si
      secretName: manipulacija-tls
  rules:
    - host: api.manipulacija.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manipulacija
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manipulacija-frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - manipulacija.lb.djnd.si
      secretName: manipulacija-frontend-tls
  rules:
    - host: manipulacija.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manipulacija-frontend
                port:
                  number: 80
