apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: razkrinkaj-ai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.razkrinkaj-ai.lb.djnd.si
      secretName: razkrinkaj-ai-tls
  rules:
    - host: api.razkrinkaj-ai.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: razkrinkaj-ai
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: razkrinkaj-ai-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.razkrinkaj-ai.lb.djnd.si
      secretName: razkrinkaj-ai-nginx-tls
  rules:
    - host: files.razkrinkaj-ai.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: razkrinkaj-ai-nginx
                port:
                  number: 80
