apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kvizle-dz-2026-backend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.kvizle.si
      secretName: kvizle-dz-2026-backend-tls
  rules:
    - host: api.kvizle.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kvizle-dz-2026-backend
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kvizle-dz-2026-frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kvizle.si
      secretName: kvizle-dz-2026-frontend-tls
  rules:
    - host: kvizle.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kvizle-dz-2026-frontend
                port:
                  number: 80
