apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razkrinkaj-ai
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razkrinkaj-ai-backend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-backend
    newTag: 'a66686927a1c22f70d57751702ecc33d52001f40'
  - name: razkrinkaj-ai-frontend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-frontend
    newTag: 'a66686927a1c22f70d57751702ecc33d52001f40'
