apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razkrinkaj-ai
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razkrinkaj-ai-backend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-backend
    newTag: 'ab4c5b9971e20f2a6ea3ec9e7f966bb1ca881599'
  - name: razkrinkaj-ai-frontend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-frontend
    newTag: 'ab4c5b9971e20f2a6ea3ec9e7f966bb1ca881599'
