apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razkrinkaj-ai
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razkrinkaj-ai-backend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-backend
    newTag: '8481983c0594ce181301e44635bd2bf489d69486'
  - name: razkrinkaj-ai-frontend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-frontend
    newTag: '8481983c0594ce181301e44635bd2bf489d69486'
