apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razkrinkaj-ai
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razkrinkaj-ai-backend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-backend
    newTag: '501ed175d4fa33573f1883e3aef1a95445359857'
  - name: razkrinkaj-ai-frontend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-frontend
    newTag: '501ed175d4fa33573f1883e3aef1a95445359857'
