apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kvizle
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: kvizle-dz-2026-backend
    newName: rg.fr-par.scw.cloud/djnd/kvizle-dz-2026-backend
    newTag: '72c47356c2504c44647074cd8fbe6daa69116663'
  - name: kvizle-dz-2026-frontend
    newName: rg.fr-par.scw.cloud/djnd/kvizle-dz-2026-frontend
    newTag: '72c47356c2504c44647074cd8fbe6daa69116663'
