apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manipulacija
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: manipulacija-backend
    newName: rg.fr-par.scw.cloud/djnd/manipulacija-backend
    newTag: '14b5658eb587aa6f64159ddbfd7b65a5fa2096cf'
  - name: manipulacija-frontend
    newName: rg.fr-par.scw.cloud/djnd/manipulacija-frontend
    newTag: '14b5658eb587aa6f64159ddbfd7b65a5fa2096cf'
