apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razkrinkaj-ai
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razkrinkaj-ai-backend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-backend
    newTag: 'e1fc694e2d0edbf256396df15c5fa8a86cd15de1'
  - name: razkrinkaj-ai-frontend
    newName: rg.fr-par.scw.cloud/djnd/razkrinkaj-ai-frontend
    newTag: 'e1fc694e2d0edbf256396df15c5fa8a86cd15de1'
