apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manipulacija
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: manipulacija-backend
    newName: rg.fr-par.scw.cloud/djnd/manipulacija-backend
    newTag: 'dfd44581c097ca97e538c7e3834eb88022ddcab9'
  - name: manipulacija-frontend
    newName: rg.fr-par.scw.cloud/djnd/manipulacija-frontend
    newTag: 'dfd44581c097ca97e538c7e3834eb88022ddcab9'
