apiVersion: v1
kind: Service
metadata:
  name: kvizle-dz-2026-bakcend
spec:
  selector:
    app: kvizle-dz-2026
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kvizle-dz-2026-frontend
spec:
  selector:
    app: kvizle-dz-2026
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
