volumes:
  postgres-data:


services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: changeme

  wagtail:
    build: ./backend
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_NAME: wagtail
      DJANGO_DATABASE_USER: wagtail
      DJANGO_DATABASE_PASSWORD: changeme
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL_BASE=http://localhost:8000
    volumes:
      - ./frontend/public:/app/public:delegated,rw
      - ./frontend/src:/app/src:delegated,rw
      - ./frontend/eslint.config.js:/app/eslint.config.js:delegated,rw
      - ./frontend/.prettierrc.json:/app/.prettierrc.json:delegated,rw
      - ./frontend/index.html:/app/index.html:delegated,rw
      - ./frontend/tsconfig.json:/app/tsconfig.json:delegated,rw
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json:delegated,rw
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json:delegated,rw
      - ./frontend/vite.config.ts:/app/vite.config.ts:delegated,rw
    depends_on:
      - wagtail
