volumes:
  postgres-data:


services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: changeme

  wagtail:
    build: ./backend
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_NAME: wagtail
      DJANGO_DATABASE_USER: wagtail
      DJANGO_DATABASE_PASSWORD: changeme
    depends_on:
      - db
