# Generated by Django 5.0.9 on 2024-10-22 15:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_chaptertextsubpage_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterquizsubpage",
            name="answers",
            field=wagtail.fields.StreamField(
                [("answer", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Besedilo"}),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Pravilno", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("correct", 1)]],
                        {"label": "Odgovor"},
                    ),
                },
                verbose_name="Odgovori",
            ),
        ),
    ]
