# Generated by Django 5.0.9 on 2024-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_chapterquizsubpage_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterquizsubpage",
            name="question",
            field=models.TextField(blank=True, verbose_name="Vprašanje"),
        ),
    ]
