# Generated by Django 5.0.9 on 2024-11-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_chapterquizsubpage_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageAnswerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_index", models.IntegerField(verbose_name="Indeks odgovora")),
                ("correct", models.BooleanField(verbose_name="Pravilno")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.chapterquizsubpage",
                        verbose_name="Stran",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odgovor na stran",
                "verbose_name_plural": "Odgovori na stran",
            },
        ),
        migrations.CreateModel(
            name="FinishedChapterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Končano ob"),
                ),
                (
                    "user_guid",
                    models.CharField(max_length=255, verbose_name="Uporabnik"),
                ),
                ("score", models.IntegerField(verbose_name="Število točk")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.chapterpage",
                        verbose_name="Poglavje",
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        to="home.pageanswerdata", verbose_name="Odgovori"
                    ),
                ),
            ],
            options={
                "verbose_name": "Končano poglavje",
                "verbose_name_plural": "Končana poglavja",
            },
        ),
    ]
