# Generated by Django 5.0.9 on 2024-12-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_pageanswerdata_finishedchapterdata"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterpage",
            name="is_feedback",
            field=models.BooleanField(default=False, verbose_name="Je anketa"),
        ),
        migrations.AlterField(
            model_name="chapterpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Slika (če je SVG formata, bo barva #9BF37E zamenjana z drugo barvo glede na stanje)",
            ),
        ),
    ]
