# Generated by Django 5.0.9 on 2024-12-19 16:05

from django.db import migrations, models


def set_finished(apps, schema_editor):
    FinishedChapterData = apps.get_model("home", "FinishedChapterData")
    FinishedChapterData.objects.update(is_finished=True)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_chapterpage_is_feedback_alter_chapterpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishedchapterdata",
            name="attempt_guid",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID poskusa"
            ),
        ),
        migrations.AddField(
            model_name="finishedchapterdata",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Poglavje končano"),
        ),
        migrations.RunPython(set_finished, migrations.RunPython.noop),
    ]
