# Generated by Django 5.0.9 on 2025-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_pageanswerdata_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="button_text_secondary",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Besedilo drugega gumba"
            ),
        ),
    ]
