# Generated by Django 5.0.9 on 2025-09-09 21:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homepage_button_text_secondary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManipulationExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ime")),
                ("description", models.CharField(max_length=255, verbose_name="Opis")),
                ("content", wagtail.fields.RichTextField(verbose_name="Vsebina")),
                ("order", models.IntegerField(default=0, verbose_name="Vrstni red")),
            ],
            options={
                "verbose_name": "Razlaga manipulacije",
                "verbose_name_plural": "Razlage manipulacij",
                "ordering": ["order"],
            },
        ),
    ]
