# Generated by Django 5.0.9 on 2025-09-30 12:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_manipulationexplanation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterquizsubpage",
            name="source_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Vir"),
        ),
    ]
