# Generated by Django 5.0.9 on 2025-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_chapterquizsubpage_source_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="NicknameEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vnešeno ob"),
                ),
                (
                    "user_guid",
                    models.CharField(max_length=255, verbose_name="Uporabnik"),
                ),
                (
                    "attempt_guid",
                    models.CharField(max_length=255, verbose_name="ID poskusa"),
                ),
                ("nickname", models.CharField(max_length=255, verbose_name="Vzdevek")),
            ],
            options={
                "verbose_name": "Vzdevek",
                "verbose_name_plural": "Vzdevki",
            },
        ),
    ]
